[package]
name = "rush"
version = "0.0.1"
authors = ["Amarnath Patel (jeebuscrossaint)"]
edition = "2018"

[dependencies]
termion = "1.5.6"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
rustyline = "8.0.0"
once_cell = "1.8.0"
rand = "0.8.4"